.TH morgenlichtctl 1 "July 2016" morgenlichtctl "User Manual"

.SH NAME
.PP
morgenlichtctl \- command\-line client for morgenlichtd(1)


.SH SYNOPSIS

.SH DESCRIPTION

.SH EXAMPLES

.SH AUTHORS
.PP
Written by Bennett Piater and Andreas Postel. Soli Deo Gloria!


.SH REPORTING BUGS
.PP
File an issue at 
\[la]http://github.com/ClawOfLight/morgenlichtctl\[ra]


.SH COPYRIGHT
.PP
Copyright © 2016 Bennett Piater. Licensed GPLv3: GNU GPL version 3 
\[la]http://gnu.org/licenses/gpl.html\[ra]
This is free software: you are welcome to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


.SH SEE ALSO
.PP
\fBmorgenlichtd\fP(1), \fBmorgenlicht\fP(7)
