Morgenlichtctl: networking.h File Reference
networking.h File Reference
This file provides an abstraction layer for the network connection to the morgenlichtd server.
#include <SDL2/SDL_net.h>
Macros
#define MORGENLICHTD_PORT 1234
The public port of morgenlichtd.
Functions
int init_networking (const char *const remote_host)
Initialise the required libraries and the TCP connection to the server.
void term_networking ()
Close the TCP connection if it is still active, then de-initialize the used libraries.
int network_write (const char *const message)
Send a message to the server via TCP.
int network_read (int maxlen, char *const buff)
Read a message sent from the server via TCP.
char network_read_char ()
Read a single char from the server.
Detailed Description
This file provides an abstraction layer for the network connection to the morgenlichtd server.
Macro Definition Documentation
MORGENLICHTD_PORT
#define MORGENLICHTD_PORT 1234
The public port of morgenlichtd.
Todo:
choose a proper port :)
Referenced by init_networking().
Function Documentation
init_networking()
int init_networking (const char *const remote_host)
Initialise the required libraries and the TCP connection to the server.
This must be called before using the other functions provided by this header.
Parameters
remote_host The host name of the server
Returns
0 on success, or non-zero otherwise.
References MORGENLICHTD_PORT.
Referenced by server_info().
network_read()
int network_read (int maxlen, char *const buff)
Read a message sent from the server via TCP.
Parameters
maxlen The length of the receiving buffer
buff The buffer in which to save the reply
Returns
0 on success, or non-zero otherwise.
network_read_char()
char network_read_char ()
Read a single char from the server.
Returns
The read character, or -1 on error.
Referenced by parse_response().
network_write()
int network_write (const char *const message)
Send a message to the server via TCP.
Parameters
message The message to send
Returns
0 on success, or non-zero otherwise.
Referenced by server_info().