Morgenlichtctl: protocol_utils.h File Reference
protocol_utils.h File Reference
This file provides helpers for common protocol functionality and basic queries.
#include "networking.h"
#include <string.h>
#include <stdlib.h>
Enumerations
enum AlarmCmd { AlarmEnable, AlarmDisable, AlarmDelete }
Basic alarm commands.
Functions
int parse_response (char *status, char **payload)
Read and parse a response from the server.
int server_info (const char *const hostname, const int port)
Print out some basic info about a morgenlichtd server.
int alarm_basic_cmd (const char *const hostname, const int port, const char *const profile, enum AlarmCmd cmd)
Perform the most basic alarm commands.
int alarm_list (const char *const hostname, const int port)
List all alarms on the server.
int alarm_add (const char *const hostname, const int port, const char *const profile, const int hour, const int minute, const int second, const char *const active_days, const char *const color, const char *const sound)
Add a new alarm or update an existing one.
Detailed Description
This file provides helpers for common protocol functionality and basic queries.
Function Documentation
alarm_add()
int alarm_add (const char *const hostname, const int port, const char *const profile, const int hour, const int minute, const int second, const char *const active_days, const char *const color, const char *const sound)
Add a new alarm or update an existing one.
Parameters
hostname The hostname of the server
port The port of the server
profile The alarm profile to create or overwrite
hour The trigger hour
minute The trigger minute
second The trigger second
active_days The days on which the profile is active
color The color profile
sound The sound file
Returns
0 on success, or non-zero otherwise.
References init_networking(), network_write(), parse_response(), and term_networking().
alarm_basic_cmd()
int alarm_basic_cmd (const char *const hostname, const int port, const char *const profile, enum AlarmCmd cmd)
Perform the most basic alarm commands.
These only require the profile name as argument and return success or failure, which makes them specially simple to implement.
Parameters
hostname The hostname of the server
port The port of the server
profile The alarm profile to act upon
cmd The command to execute
Returns
0 on success, or non-zero otherwise.
References init_networking().
alarm_list()
int alarm_list (const char *const hostname, const int port)
List all alarms on the server.
Parameters
hostname The hostname of the server
port The port of the server
Returns
0 on success, or non-zero otherwise.
Print the alarm
Todo:
: make this pretty, yet work decently with many alarms.
References init_networking(), network_write(), and parse_response().
parse_response()
int parse_response (char * status, char ** payload)
Read and parse a response from the server.
This will print out the warning if the server sent one, parse the status code and payload, write the status code to the given char, and allocate memory for the payload.
Note
The payload will have to be free'd by the caller, as it is dynamically allocated.
Parameters
status Address of a char to which to write the status code.
payload Pointer to a char pointer that will point to the payload.
Returns
0 on success, or non-zero otherwise.
References network_read_char(), and term_networking().
Referenced by alarm_add(), alarm_list(), and server_info().
server_info()
int server_info (const char *const hostname, const int port)
Print out some basic info about a morgenlichtd server.
Parameters
hostname The hostname of the server
port The port of the server
Returns
0 on success, or non-zero otherwise.
References init_networking(), network_write(), parse_response(), and term_networking().